package mascotas.ui;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import exceptions.NoExisteException;
import mascotas.Cliente;
import mascotas.Mainn;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Window.Type;

public class AgregarEnPosicionCliente extends JFrame {

	private JPanel contentPane;

	/**
	 * Creates new form AgregarEnPosicionCliente
	 */
	public AgregarEnPosicionCliente() {
		setTitle("AGREGAR CLIENTE");
		setType(Type.POPUP);
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		bgOpcionesInsertarPosicion = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		rbtAlcomienzoCliente = new javax.swing.JRadioButton();
		rbtAlcomienzoCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (rbtAlcomienzoCliente.isSelected()) // Por defecto, Java asume que en una condicion booleana, es
														// verdadero y entra al IF
				{
					bandera = 0;

				}
			}
		});

		rbtAlFinalCliente = new javax.swing.JRadioButton();
		rbtAlFinalCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (rbtAlFinalCliente.isSelected()) {
					bandera = 1;
				}
			}
		});
		rbtAntesCliente = new javax.swing.JRadioButton();
		rbtAntesCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (rbtAntesCliente.isSelected()) {
					bandera = 2;
				}
			}
		});
		rbtDespuesCliente = new javax.swing.JRadioButton();
		rbtDespuesCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (rbtDespuesCliente.isSelected()) {
					bandera = 3;
				}
			}
		});
		txtDespuesDeEsteCodigo = new javax.swing.JTextField();
		txtAntesDeEsteCodigo = new javax.swing.JTextField();
		btnCancelarPosicion = new javax.swing.JButton();
		btnCancelarPosicion.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new AgregarCliente().setVisible(true);
				AgregarEnPosicionCliente.this.dispose();

			}
		});
		btnFinalizarPosicion = new javax.swing.JButton();
		btnFinalizarPosicion.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (bgOpcionesInsertarPosicion.getSelection() != null) {
					switch (bandera) {
					case 0:
						Mainn.cliente.insertarInicio(clienteTemporal);
						break;
					case 1:
						Mainn.cliente.insertarFinal(clienteTemporal);
						break;
					case 2:
						try {
							Mainn.cliente.insertarAntesDe(Integer.valueOf(txtAntesDeEsteCodigo.getText()),
									clienteTemporal);

						} catch (NoExisteException e2) {
							JOptionPane.showMessageDialog(AgregarEnPosicionCliente.this,
									"No hay un código como referencia.", "ERROR", JOptionPane.ERROR_MESSAGE);// Mensaje
																												// bonito
							return;
						}
						break;
					case 3:
						try {
							Mainn.cliente.insertarDespuesDe(Integer.valueOf(txtDespuesDeEsteCodigo.getText()),
									clienteTemporal);

						} catch (NoExisteException e2) {
							JOptionPane.showMessageDialog(AgregarEnPosicionCliente.this,
									"No hay un código como referencia.", "ERROR", JOptionPane.ERROR_MESSAGE);// Mensaje
																												// bonito
							return;
						}

						break;
					default:
						break;
					}

					JOptionPane.showMessageDialog(null, "Se ha agregado exitosamente");
					AgregarEnPosicionCliente.this.dispose();
					new GestionDeClientes().setVisible(true);

				} else {
				JOptionPane.showMessageDialog(AgregarEnPosicionCliente.this, "No has seleccionado ninguna opción", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(
				javax.swing.BorderFactory.createTitledBorder(null, "Opciones ", javax.swing.border.TitledBorder.CENTER,
						javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 13))); // NOI18N

		bgOpcionesInsertarPosicion.add(rbtAlcomienzoCliente);
		rbtAlcomienzoCliente.setText("Al comienzo de la lista.");

		bgOpcionesInsertarPosicion.add(rbtAlFinalCliente);
		rbtAlFinalCliente.setText("Al final de la lista.");

		bgOpcionesInsertarPosicion.add(rbtAntesCliente);
		rbtAntesCliente.setText("Antes del cliente con el código:");

		bgOpcionesInsertarPosicion.add(rbtDespuesCliente);
		rbtDespuesCliente.setText("Después del cliente con el código:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(rbtAlFinalCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(rbtAntesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(rbtDespuesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(24, 24, 24)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtDespuesDeEsteCodigo).addComponent(txtAntesDeEsteCodigo))
						.addContainerGap())
				.addComponent(rbtAlcomienzoCliente, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(7, 7, 7)
						.addComponent(rbtAlcomienzoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(rbtAlFinalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(rbtAntesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtAntesDeEsteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(rbtDespuesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtDespuesDeEsteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnCancelarPosicion.setText("Cancelar");

		btnFinalizarPosicion.setText("Finalizar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(34, 34, 34)
						.addComponent(btnCancelarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 126,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnFinalizarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 126,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(32, 32, 32)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnCancelarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnFinalizarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(14, 14, 14)));

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AgregarEnPosicionCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AgregarEnPosicionCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AgregarEnPosicionCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AgregarEnPosicionCliente.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AgregarEnPosicionCliente().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup bgOpcionesInsertarPosicion;
	private javax.swing.JButton btnCancelarPosicion;
	private javax.swing.JButton btnFinalizarPosicion;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton rbtAlcomienzoCliente;
	private javax.swing.JRadioButton rbtAlFinalCliente;
	private javax.swing.JRadioButton rbtAntesCliente;
	private javax.swing.JRadioButton rbtDespuesCliente;
	private javax.swing.JTextField txtAntesDeEsteCodigo;
	private javax.swing.JTextField txtDespuesDeEsteCodigo;
	public static Cliente clienteTemporal;
	private int bandera = 0;// Por defecto con el int se inicializa en o con Integer si hay que inicializar
	// End of variables declaration
}
