package mascotas.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import mascotas.Mainn;
import modelo.miModeloCliente;
import javax.swing.JButton;

/**
 *
 * @author camilavargas
 */
public class GestionDeClientes extends javax.swing.JFrame {

	public static int filaSeleccionada;
	
	/**
	 * Creates new form GestionDeClientes
	 */
	public GestionDeClientes() {
		setTitle("Gestión de clientes.");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jScrollPane2.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				int row = tablaCliente.getSelectedRow();
				if (row > -1) {
				}
			}
		});
		tablaCliente = new javax.swing.JTable();

		btnAgregarCliente = new javax.swing.JButton();
		btnAgregarCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new AgregarCliente().setVisible(true);
				GestionDeClientes.this.dispose();
			}
		});
		btnBuscarCliente = new javax.swing.JButton();
		btnBuscarCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new BuscarCliente().setVisible(true);
				GestionDeClientes.this.dispose();
			}
		});
		btnVerMascotas = new javax.swing.JButton();
		btnVerMascotas.setEnabled(false);
		btnVerMascotas.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (identificacionCliente != -1) {
					GestionDeMascotas vista = new GestionDeMascotas(Mainn.cliente.buscarCliente(identificacionCliente).getMascota());
					vista.setVisible(true);
					GestionDeClientes.this.dispose();
				}
				
			}
		});
		BtnEliminarCliente = new javax.swing.JButton();
		BtnEliminarCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new EliminarCliente().setVisible(true);
				GestionDeClientes.this.dispose();
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		tablaCliente.setModel(new miModeloCliente(Mainn.cliente));
	
		ListSelectionModel model = tablaCliente.getSelectionModel();
		model.addListSelectionListener(new ListSelectionListener() {
			
			public void valueChanged(ListSelectionEvent e) {
				if(! model.isSelectionEmpty()) {
					filaSeleccionada = model.getMinSelectionIndex();
					identificacionCliente = (int) tablaCliente.getValueAt(filaSeleccionada, 0);
					btnVerMascotas.setEnabled(true);
				}
			}
		});
		
		tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tableClientesMouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(tablaCliente);

		btnAgregarCliente.setText("Agregar");

		btnBuscarCliente.setText("Buscar");

		btnVerMascotas.setText("Ver Mascotas");

		BtnEliminarCliente.setText("Eliminar");
		
		JButton btnRegresar = new JButton();
		btnRegresar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new MenuPrincipal().setVisible(true);
				dispose();
			}
		});
		btnRegresar.setText("Regresar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
							.addContainerGap())
						.addGroup(layout.createSequentialGroup()
							.addComponent(btnAgregarCliente, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnBuscarCliente, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(BtnEliminarCliente, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnVerMascotas, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
							.addComponent(btnRegresar, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
							.addGap(21))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.CENTER)
						.addComponent(btnAgregarCliente, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnBuscarCliente, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
						.addComponent(BtnEliminarCliente, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnVerMascotas, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnRegresar, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

	private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GestionDeClientes.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GestionDeClientes().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton BtnEliminarCliente;
	private javax.swing.JButton btnAgregarCliente;
	private javax.swing.JButton btnBuscarCliente;
	private javax.swing.JButton btnVerMascotas;
	private javax.swing.JScrollPane jScrollPane2;
	private int identificacionCliente = -1;
	public static javax.swing.JTable tablaCliente;
}
