package mascotas.ui;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import mascotas.Mainn;
import mascotas.centralMascota;
import modelo.miModeloMascota;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Window.Type;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.SwingConstants;

public class GestionDeMascotas extends JFrame {

	private JPanel contentPane;

    /**
     * Creates new form GestionDeMascotas
     */
    public GestionDeMascotas(centralMascota mascotasCliente) {
    	this.mascotasCliente = mascotasCliente;
    	setFont(new Font("Comic Sans MS", Font.BOLD, 12));
    	setType(Type.POPUP);
    	setTitle("GESTIÓN DE MASCOTAS");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BtnEliminarMascota = new javax.swing.JButton();
        BtnEliminarMascota.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new EliminarMascota(mascotasCliente).setVisible(true);
        		GestionDeMascotas.this.dispose();
        	}
        });
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMascota = new javax.swing.JTable();
        btnAgregarMascota = new javax.swing.JButton();
        btnAgregarMascota.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new AgregarMascota(mascotasCliente).setVisible(true);
        		GestionDeMascotas.this.dispose();
        	}
        });
        btnBuscarMascota = new javax.swing.JButton();
        btnBuscarMascota.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new BuscarMascota(mascotasCliente).setVisible(true);
        		GestionDeMascotas.this.dispose();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnEliminarMascota.setText("Eliminar");

        //tableMascota.setModel(new miModeloMascota(Mainn.mascota));
        
        tableMascota.setModel(new miModeloMascota(mascotasCliente));
        tableMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMascota);

        btnAgregarMascota.setText("Agregar");

        btnBuscarMascota.setText("Buscar");
        
        JButton btnAtras = new JButton("Atras");
        btnAtras.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new GestionDeClientes().setVisible(true);
				dispose();
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnAgregarMascota, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnBuscarMascota, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(BtnEliminarMascota, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnAtras, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.CENTER)
        				.addComponent(btnAgregarMascota, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBuscarMascota, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        				.addComponent(BtnEliminarMascota, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnAtras, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnEliminarMascota;
    private javax.swing.JButton btnAgregarMascota;
    private javax.swing.JButton btnBuscarMascota;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableMascota;
    private centralMascota mascotasCliente;
}
